name: Release Windows EXE

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Verify inputs
        run: |
          if (!(Test-Path "YIFY-Subtitle-Downloader.py")) { Write-Error "YIFY-Subtitle-Downloader.py not found" }
          if (!(Test-Path "icon.png")) { Write-Error "icon.png not found in repo root" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests

      - name: Build EXE (embed icon.png)
        shell: pwsh
        run: |
          pyinstaller --noconfirm --onefile --windowed `
            --name "YIFY-Subtitle-Downloader" `
            --add-data "icon.png;." `
            YIFY-Subtitle-Downloader.py

      - name: Verify & rename with tag
        shell: pwsh
        run: |
          $exe = "dist\YIFY-Subtitle-Downloader.exe"
          if (!(Test-Path $exe)) { Write-Error "Build failed: $exe not found" }
          $tag = "${{ github.ref_name }}"
          Move-Item $exe ("dist\YIFY-Subtitle-Downloader-$tag.exe") -Force

      - name: Create GitHub Release and upload EXE
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/YIFY-Subtitle-Downloader-${{ github.ref_name }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
